config/routes.rb
JackyGameChest::Application.routes.draw do

  root 'application#home'

  namespace :board_games do
    get 'tic_tac_toe' => 'tic_tac_toes#play'
  end

  namespace :api do
    namespace :board_games do
      namespace :tic_tac_toe do
        post 'cpu_makes_move'
      end
    end
  end
end

app/controllers/api/board_games/tic_tac_toe_controller.rb
module Api
  module BoardGames
    class TicTacToeController < ApplicationController

      def cpu_makes_move
        respond_to do |format|
          format.js do
            begin
              board = TicTacToe::Board.new(JSON.parse(params[:board_field]))
              cpu = TicTacToe::Computer.new(board)
              cpu.make_move
              @message = { data: { board: cpu.board.grid, status: cpu.board.status.report }, success: true }
            rescue => e
              @message = { data: { error: e.to_s }, success: false }
            end
            render "response"
          end
        end
      end

    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  layout "application"

  def home
    
  end

end

app/controllers/board_games/tic_tac_toes_controller.rb
module BoardGames
  class TicTacToesController < ApplicationController

    layout "tic_tac_toe"

    def play

    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/home.html.haml
%header
  .container
    .row
      = image_tag("home-image.png")
      .intro-text
        %h1 HIP BOARD GAMES
        .block-line
        %h2 A WALK DOWN MEMORY LANE

%section#games
  .container
    .row
      %h2 GAMES
    .row
      = link_to board_games_tic_tac_toe_path do
        .game-block.active
          %h3 CLASSY TIC-TAC-TOE
      %a
        .game-block.disabled
          %h3 MORE COMING SOON

%footer
  .container
    .row
      %h3 CONTACT ME
      %p
        %a{:href => "https://github.com/jackyl14", :target => "_blank"}
          VIA GITHUB
        %br
        %a{:href => "https://www.linkedin.com/in/jackyl14", :target => "_blank"}
          VIA LINKEDIN

app/views/board_games/tic_tac_toes/modals/_error.html.haml
.modal#errorModal
  .modal-wrapper
    .modal-header.underline
      %h2 Game Status
    .modal-body
      %h2 System Error
      %p
        %i Announcement:
        %br
        Sorry, an unexpected error has occured.
        Please cancel or try playing again.
    .modal-footer
      = link_to root_path do
        %button.cancelButton.secondary-button{ :type => "button" } Cancel
      %button.playAgainButton.primary-button.is-last{ :type => "button" } Try again!
  .overlay

app/views/board_games/tic_tac_toes/modals/_intro.html.haml
.modal#introModal.active
  .modal-wrapper
    .modal-header
      %h2 Classy Tic-Tac-Toe
    .modal-body
      %p
        %i How to Play:
        %br
        You will be taking turns, playing against a computer.
        First to get a line of three boxes (horizontally,
        vertically, or diagonally) wins all the fame and glory.
    .modal-footer
      = link_to root_path do
        %button.cancelButton.secondary-button{ :type => "button" } Cancel
      %button#playButton.primary-button.is-last{ :type => "button" } Let's play!
  .overlay

app/views/board_games/tic_tac_toes/modals/_loser.html.haml
.modal#loserModal
  .modal-wrapper
    .modal-header.underline
      %h2 Game Status
    .modal-body
      %h2 You've lost!
      %p
        %i Announcement:
        %br
        Unfortunately, your opponent has outplayed you, and you were doomed from the start.
    .modal-footer
      = link_to root_path do
        %button.cancelButton.secondary-button{ :type => "button" } Run Away
      %button.playAgainButton.primary-button.is-last{ :type => "button" } Play again!
  .overlay

app/views/board_games/tic_tac_toes/modals/_player.html.haml
.modal#playerModal
  .modal-wrapper
    .modal-header
      %h2 Game Play
    .modal-body
      %p
        %i Announcement:
        %br
        Now, let the games begin, and may the odds forever be in your favor!
        Please pick if you want to go first or second.
    .modal-footer
      %button#firstPlayerButton.secondary-button{ :type => "button", :value => "1" } First
      %button#secondPlayerButton.primary-button.is-last{ :type => "button", :value => "2" } Second
  .overlay

app/views/board_games/tic_tac_toes/modals/_tie.html.haml
.modal#tieModal
  .modal-wrapper
    .modal-header.underline
      %h2 Game Status
    .modal-body
      %h2 TIE!
      %p
        %i Announcement:
        %br
        Wow, you are quite the opponent, but I bet you just got lucky.
    .modal-footer
      = link_to root_path do
        %button.cancelButton.secondary-button{ :type => "button" } Quit
      %button.playAgainButton.primary-button.is-last{ :type => "button" } Feeling lucky!
  .overlay

app/views/board_games/tic_tac_toes/modals/_winner.html.haml
.modal#winnerModal
  .modal-wrapper
    .modal-header.underline
      %h2 Game Status
    .modal-body
      %h2 You've won!
      %p
        %i Announcement:
        %br
        Congratulations! You have gone through trial by fire and have beaten the odds.
    .modal-footer
      = link_to root_path do
        %button.cancelButton.secondary-button{ :type => "button" } Quit
      %button.playAgainButton.primary-button.is-last{ :type => "button" } Win again!
  .overlay

app/views/board_games/tic_tac_toes/play.html.haml
.game-content
  #tic-tac-toe-board
    %table
      %tbody
        %tr.top-row.row-1
          %td.first-column.col-1
          %td.middle-column.col-2
          %td.last-column.col-3
        %tr.middle-row.row-2
          %td.first-column.col-1
          %td.middle-column.col-2
          %td.last-column.col-3
        %tr.last-row.row-3
          %td.first-column.col-1
          %td.middle-column.col-2
          %td.last-column.col-3

= render "board_games/tic_tac_toes/modals/intro"
= render "board_games/tic_tac_toes/modals/player"
= render "board_games/tic_tac_toes/modals/winner"
= render "board_games/tic_tac_toes/modals/loser"
= render "board_games/tic_tac_toes/modals/tie"
= render "board_games/tic_tac_toes/modals/error"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title JackyGameChest
    = stylesheet_link_tag    "application", media: "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    = render "partials/header"
    = yield

app/views/layouts/tic_tac_toe.html.haml
!!!
%html
  %head
    %title JackyGameChest || Tic Tac Toe
    = stylesheet_link_tag    "application", media: "all"
    = stylesheet_link_tag    "tic-tac-toe", media: "all"
    = javascript_include_tag "tic-tac-toe"
    = csrf_meta_tags
  %body
    = render "partials/header"
    = yield

app/views/partials/_header.html.haml
%nav
  .container
    .nav-brand
      %a{:href => ""} JACKY GAME CHEST
    .nav-list
      %ul
        %li
          = link_to "GAMES", root_path(anchor: "games"), id: "gameSection"